package other

/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'insulaventus' at '9/13/16 8:54 PM' with Gradle 2.7
 *
 * @author insulaventus, @date 9/13/16 8:54 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
